### PR TITLE
docs: Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Perumallpardhiv**
Fixes: #43 
Added CONTRIBUTING.md file
Once check it!
Thank you

### CODE REVIEW

**Comment by Perumallpardhiv** [comment]
@rrousselGit 
Guide me, If any changes are required in this CONTRIBUTING.md

**Comment by rrousselGit** [comment]
Thanks!

**Comment by Perumallpardhiv** [comment]
@rrousselGit 

Sir, is this pr counted in Invertase Rewards or It will take some time to count ?

**Comment by rrousselGit** [comment]
I've labeled it accordingly. It should count

**Comment by Perumallpardhiv** [comment]
@rrousselGit 
It is not showing sir

image

**Comment by Perumallpardhiv** [comment]
Thank you sir
Have a nice day

**Comment by Perumallpardhiv** [comment]
@rrousselGit 
Sir, how can I claim the invertase rewards which got due to contribution in this #45 merged pr ??

image

**Pull request merged**
